// <auto-generated />
using System;
using AiMoodCompanion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiMoodCompanion.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250810112840_AddMoreRecommendations")]
    partial class AddMoreRecommendations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiMoodCompanion.Api.Models.ModelVersions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double>("Precision")
                        .HasColumnType("double precision");

                    b.Property<double>("Recall")
                        .HasColumnType("double precision");

                    b.Property<int>("TrainingDataCount")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.MoodAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedMood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<double>("MoodScore")
                        .HasColumnType("double precision");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MoodAnalyses");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recommendations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(515),
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Genre = "Drama",
                            ImageUrl = "https://example.com/shawshank.jpg",
                            Title = "The Shawshank Redemption",
                            Type = "Movie",
                            Year = 1994
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(520),
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.",
                            Genre = "Fantasy",
                            ImageUrl = "https://example.com/lotr.jpg",
                            Title = "The Lord of the Rings",
                            Type = "Movie",
                            Year = 2001
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(523),
                            Description = "A dystopian novel about a totalitarian society where Big Brother is always watching.",
                            Genre = "Dystopian",
                            ImageUrl = "https://example.com/1984.jpg",
                            Title = "1984",
                            Type = "Book",
                            Year = 1949
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(525),
                            Description = "A high school chemistry teacher turned methamphetamine manufacturer partners with a former student.",
                            Genre = "Crime",
                            ImageUrl = "https://example.com/breaking-bad.jpg",
                            Title = "Breaking Bad",
                            Type = "Series",
                            Year = 2008
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(527),
                            Description = "A legendary concierge and his young protégé embark on a series of adventures.",
                            Genre = "Comedy",
                            ImageUrl = "https://example.com/grand-budapest.jpg",
                            Title = "The Grand Budapest Hotel",
                            Type = "Movie",
                            Year = 2014
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(532),
                            Description = "A jazz pianist falls for an aspiring actress in Los Angeles.",
                            Genre = "Romance",
                            ImageUrl = "https://example.com/lalaland.jpg",
                            Title = "La La Land",
                            Type = "Movie",
                            Year = 2016
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(534),
                            Description = "A woman rebels against a tyrannical ruler in post-apocalyptic Australia.",
                            Genre = "Action",
                            ImageUrl = "https://example.com/madmax.jpg",
                            Title = "Mad Max: Fury Road",
                            Type = "Movie",
                            Year = 2015
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(536),
                            Description = "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence.",
                            Genre = "Horror",
                            ImageUrl = "https://example.com/conjuring.jpg",
                            Title = "The Conjuring",
                            Type = "Movie",
                            Year = 2013
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(537),
                            Description = "Documentary series exploring the natural world and its wonders.",
                            Genre = "Documentary",
                            ImageUrl = "https://example.com/planetearth.jpg",
                            Title = "Planet Earth II",
                            Type = "Series",
                            Year = 2016
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 10, 11, 28, 40, 11, DateTimeKind.Utc).AddTicks(541),
                            Description = "An astronaut becomes stranded on Mars and must find a way to survive.",
                            Genre = "Adventure",
                            ImageUrl = "https://example.com/martian.jpg",
                            Title = "The Martian",
                            Type = "Movie",
                            Year = 2015
                        });
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.TrainingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedMood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUsedForTraining")
                        .HasColumnType("boolean");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<double>("MoodScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UsedForTrainingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserFeedback")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingData");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.UserReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserReactions");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.MoodAnalysis", b =>
                {
                    b.HasOne("AiMoodCompanion.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.Recommendation", b =>
                {
                    b.HasOne("AiMoodCompanion.Api.Models.User", null)
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.TrainingData", b =>
                {
                    b.HasOne("AiMoodCompanion.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.UserReaction", b =>
                {
                    b.HasOne("AiMoodCompanion.Api.Models.Recommendation", "Recommendation")
                        .WithMany("UserReactions")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiMoodCompanion.Api.Models.User", "User")
                        .WithMany("UserReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.Recommendation", b =>
                {
                    b.Navigation("UserReactions");
                });

            modelBuilder.Entity("AiMoodCompanion.Api.Models.User", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("UserReactions");
                });
#pragma warning restore 612, 618
        }
    }
}
